name: Laravel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel-mix:
    name: Laravel Mix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Npm Build
        run: |
          npm install
          npm run prod
          cat public/mix-manifest.json
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  laravel-tests:
    name: Laravel Tests
    needs: laravel-mix
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Create Database
        run: |
         mkdir -p database
         touch database/database.sqlite
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Optimization
        run: php artisan optimize:clear
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml
          bash <(curl -s https://codecov.io/bash)
      - name: Check code style violations
        run: vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots
      - name: PHP Insights
        run: php artisan insights
